### PR TITLE
Improve pants.pex startup latency.

### PR DESCRIPTION
**Pull request by jsirois**
Also dogfood pexes here and just wget the official Pex PEX.

### CODE REVIEW

**Comment by jsirois** [comment]
This is mainly an FYI on newer Pex as well as some Pex options you might leverage.

The results:
```
$ touch BUILDROOT ../frozenpants/BUILDROOT
$ hyperfine --warmup 2 './pants.pex --version' '../frozenpants/pants.pex --version'
Benchmark #1: ./pants.pex --version
  Time (mean ± σ):      2.236 s ±  0.028 s    [User: 1.794 s, System: 0.282 s]
  Range (min … max):    2.206 s …  2.296 s    10 runs
 
Benchmark #2: ../frozenpants/pants.pex --version
  Time (mean ± σ):      3.468 s ±  0.014 s    [User: 2.994 s, System: 0.309 s]
  Range (min … max):    3.441 s …  3.490 s    10 runs
 
Summary
  './pants.pex --version' ran
    1.55 ± 0.02 times faster than '../frozenpants/pants.pex --version'

```

**Comment by jsirois** [comment]
We were guilty of missing this optimization over in Pants too!: https://github.com/pantsbuild/pants/pull/11591

**Comment by slackhappy** [comment]
Wow, so sorry I missed this! @jsirois himself!  This looks great!  the only issue I see when I check it out and build is that the python shebang at the top of pants.pex for the MacOS build ends up being changed from:
```
#!/usr/bin/env python3.8
```
to 
```
#!/usr/bin/env python3.6
```

however, macos catalina and big sur only have python3.8 installed by default (i think), so my github actions build wants to build for that version. The goal is basically to allow pants to run on a system without any additional python gymnastics.  (Maybe i could even get a matrix build going for multiple python versions)

image


Any ideas on the best way to support that?  It at least looks like `pex` itself is not really python version dependent when i dump the contents of `pex-2.1.31.pex`.

**Comment by slackhappy** [comment]
Not sure why the build job doesn't run on your PR.  I was able to get the macos version built under python 3.8 locally with the correct shebang like this :

```diff
--- a/build.sh
+++ b/build.sh
@@ -12,5 +12,5 @@ elif [ "$(uname)" == 'Darwin' ]; then
     # python3.8 because xcode won't compile python c libs
     # against it, but downloading a new tarball works
     ./pyenv.sh 3.8.7
-    PYTHON_PATH=.deps/pyenv/versions/3.8.7/bin/python3 ./build_pex.sh
+    PYTHON=.deps/pyenv/versions/3.8.7/bin/python3 ./build_pex.sh
 fi
diff --git a/build_pex.sh b/build_pex.sh
index 1a268cc..e598609 100755
--- a/build_pex.sh
+++ b/build_pex.sh
@@ -7,7 +7,10 @@ set -euo pipefail

 PEX_VERSION=2.1.31
 PANTS_VERSION=1.26.0
-PANTS_INTERPRETER_CONSTRAINT="CPython==3.6.*"
+PYTHON=${PYTHON:-python3}
+PYTHON_MAJOR_MINOR=$($PYTHON --version | grep -o '3\.[0-9]*')
+PANTS_INTERPRETER_CONSTRAINT="CPython==$PYTHON_MAJOR_MINOR.*"
+echo Setting python constraint $PANTS_INTERPRETER_CONSTRAINT
```

however, it fails in CI: https://github.com/slackhappy/frozenpants/runs/2915558110  I suspect this is because, without the virtualenv, the interpreter search path is somehow picking the system python 3.8, instead of the pyenv one.  I need the pyenv one because it includes the necessary headers for compiling the python modules with C extensions, even though the eventual target (python3.8) is the same.

I'm currently debugging that in a branch: https://github.com/slackhappy/frozenpants/compare/johng_jsirois_latency_startup_improve

**Comment by slackhappy** [comment]
for now, I've accepted some of the main changes in your PR in #5:
- peg the pex version
- use `--venv` option for when building pex for faster startup
- move requirements into a separate file
- use PEX_TOOLS for dumping info

**Comment by jsirois** [comment]
So, We could build a multi-interpreter (and even multi-platform) PEX file, but the pegged Pants version in the script is 1.26.0 which _only_ supports Python 3.6: https://pypi.org/project/pantsbuild.pants/1.26.0/#files

So Pex aside, you can't do what you want with that Pants version.

As far as controlling shebang, see: `pex --help` and look for `--python-shebang`. You probably want one of these:
1. Completely neutral boot python: `--python-shebang "/usr/bin/env python"`
2. Some Python 3 version: `--python-shebang "/usr/bin/env python3"`
3. Python 3.6 or die: `--python-shebang "/usr/bin/env python3.6"`

For Pants 1.26.0 you might as well pick #3 since it can only run with Python 3.6. That will die fastest if one is not on the PATH. If you want a better error message, use #1. That will ensure the PEX file boots and it will die with a message a bit more informative about not finding an interpreter to match the interpreter constraints of the PEX file.

**Pull request closed without merging**
